name: Angular Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Build the Angular app with production settings
      - name: Build Angular app to prod
        working-directory: UserPortal-FrontEnd
        run: |
          npm install
          npm run build:prod

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # Adjust to match the actual build output folder
          branch: gh-pages  # Avoid deploying to main
          token: ${{ secrets.ANGULAR_SHIT }}  # Ensure correct secret is set
